l=list(input("Enter elements separated by space: ").split())
ele=input("Enter element to count: ")
print(l.count(ele))
ele=input("Enter element to find index of: ")
print(l.index(ele))
l.reverse()
print("Reversed list:", l)
l.sort()
print("Sorted list: ", l)
l.sort(reverse=True)
print("Sorted list in descending order: ", l)
